### ISSUE TITLE
update_ref() is unused but code does not run without it

### ISSUE THREAD

**Issue by sebreens** [spencerfolk/rotorpy#4]
Hello!

The quadrotor_control.py file contains a function 'update_ref' that is called in the simulate.py line 101. However, the controller_template.py file skips this function and the control_ref variable that is defined in that line is unused in the code. 

```powershell
Traceback (most recent call last):
  File "c:\Users\uber\Documents\autopilot_sim\rotorpy-main\attitude_flight.py", line 99, in <module>
    results = sim_instance.run(t_final      = 20,       # The maximum duration of the environment in seconds
  File "c:\Users\uber\Documents\autopilot_sim\rotorpy-main\rotorpy\environments.py", line 115, in run
    (time, state, control, flat, imu_measurements, imu_gt, mocap_measurements, state_estimate, exit) = simulate(self.world,
  File "c:\Users\uber\Documents\autopilot_sim\rotorpy-main\rotorpy\simulate.py", line 101, in simulate
    control_ref = [sanitize_control_dic(controller.update_ref(time[-1], flat[-1]))]
AttributeError: 'CustomControl' object has no attribute 'update_ref'
``` 
What is the purpose of the update_ref() function? Is it an artifact of an older implementation? It seems like it should be deleted.

**Comment by spencerfolk** [comment]
`update_ref` was added more of as a helper function to compute feedforward terms based on higher derivatives of the flat output. It was never meant to be called in the main simulation loop. Thanks for catching this :) 

I removed this line in b215519ccac1b1c8da7f9967fb32c4f633452a60
