### ISSUE TITLE
Assuming rotor directions even though they are defined in parameter files

### ISSUE THREAD

**Issue by sebreens** [spencerfolk/rotorpy#5]
https://github.com/spencerfolk/rotorpy/blob/b6ccd20ce125474c64fc39c2a970525be629f00c/rotorpy/controllers/quadrotor_control.py#L63

This line assumes that the yaw moments alternate starting from positive r1, however, the directions are given in the vehicle parameter file under rotor_dir variable, thus they can just be taken from there.
```python
np.array([k*(-1)**i for i in range(self.num_rotors)]).reshape(1,-1)
# Can be replaced with
(k * self.rotor_dir).reshape(1,-1)
``` 

It is hard to understand how exactly is the TM matrix created and what do the letters 'TM' are supposed to mean. I guess it's thrust mixing to forces/forces to thrust mixing.

@spencerfolk @shaoyifei96

**Comment by spencerfolk** [comment]
I implemented your suggestion in  29ff3b9ddf91eeff39b01d725912a08143057bea

Thanks!!
