### ISSUE TITLE
Increasing IMU noise does not destabilize the controller

### ISSUE THREAD

**Issue by sebreens** [spencerfolk/rotorpy#6]
I took the example case and added a copy of the given IMU with 100x the given noise, initial bias and random walk set at 1 on all axis. The simulation did not change a single bit, although the drone should have been completely destabilized. 

I applied the parameters in the init function:

```python
    def __init__(self, accelerometer_params={'initial_bias': np.array([1., 1., 1.]), # m/s^2
                                             'noise_density': ((0.38*100)**2)*np.ones(3,), # m/s^2 / sqrt(Hz)
                                             'random_walk': np.ones(3,) # m/s^2 * sqrt(Hz)
                                             }, 
                gyroscope_params={'initial_bias': np.array([1.,1.,1.]), # m/s^2
                                  'noise_density': ((0.01*100)**2)*np.ones(3,), # rad/s / sqrt(Hz)
                                  'random_walk': np.ones(3,) # rad/s * sqrt(Hz)
                                  }, 
                R_BS = np.eye(3),
                p_BS = np.zeros(3,),
                sampling_rate=500, 
                gravity_vector=np.array([0,0,-9.81])):
``` 

This signalizes that something is seriously off in the way the simulation works.

**Comment by spencerfolk** [comment]
Hi @sebreens, thank you for bringing this to my attention. The reason this does not affect the controller is that the current controller implementation does not actually use the IMU measurements for operation. The original purpose of the IMU measurement was to be for state estimation purposes or studying lumped parameter models of aerodynamic drag. 

You can see what information is used by the included controller in [`quadrotor_control.py`](https://github.com/spencerfolk/rotorpy/blob/main/rotorpy/controllers/quadrotor_control.py). It uses direct observations of the full state (position, velocity, attitude) to produce actions, which abstracts away the attitude estimate you might get from the IMU. 

If you want to implement a controller that uses information from the IMU, you'll need to create a new controller object. You can start with a template like [this](https://github.com/spencerfolk/rotorpy/blob/main/rotorpy/controllers/controller_template.py). 

The key difference is that you'll need to supply the controller with the IMU measurement, which will require modifying [`simulate()`](https://github.com/spencerfolk/rotorpy/blob/main/rotorpy/simulate.py) to make sure the simulator passes this information to the controller. If you develop such implementation, feel free to submit a pull request to merge it to the main branch. 

I'm reworking `simulate()` to be more flexible for different controllers but haven't had the time to make serious progress, so anything you can contribute would be valuable.
